apiVersion : apps/v1
kind: Deployment
metadata:
  name : app-api
  namespace : devops-project 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
        - name: app
          image: ghcr.io/thanutgit/devopsminiproject:v2026.03.06-5
          ports:
            - containerPort: 3010
          env:
            - name: APP_SERVICE
              value: "server"
          envFrom:
            - secretRef:
                name: devops-project-secret
            - configMapRef:
                name: devops-project-config-map
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "100m"
