apiVersion : apps/v1
kind: Deployment
metadata:
  name : app-api
  namespace : devops-project 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
      annotations:              
        prometheus.io/scrape: "true"
        prometheus.io/port: "3010"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: app
          image: ghcr.io/thanutgit/devopsminiproject:VERSION
          ports:
            - containerPort: 3010
          env:
            - name: APP_SERVICE
              value: "server"
          envFrom:
            - secretRef:
                name: devops-project-secret
            - configMapRef:
                name: devops-project-config-map
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion : v1
kind: Service
metadata:
  name: app-service
  namespace: devops-project
spec:
  selector:
    app: devops-project
  ports:
    - port: 3020
      targetPort: 3010
  type: ClusterIP
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring