apiVersion: batch/v1
kind: Job
metadata:
  name: devops-project-job
  namespace: devops-project
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 1200
  activeDeadlineSeconds: 1200
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile: 
          type: RuntimeDefault
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - name: migrate
          image: ghcr.io/thanutgit/devopsminiproject:VERSION
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          env:
            - name: APP_SERVICE
              value: "migrator"
          envFrom:
            - secretRef:
                name: devops-project-secret
            - configMapRef:
                name: devops-project-config-map
      restartPolicy: Never

