apiVersion: v1
kind: Namespace
metadata:
  name: monitoring 
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'app-api'
        static_configs:
          - targets: ['app-service.devops-project.svc.cluster.local:3010']
