---
  - name: Install k3s server
    ansible.builtin.shell: |
      curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -
    args:
      creates: /usr/local/bin/k3s
  - name: Wait for token file to be created
    ansible.builtin.wait_for:
      path: /var/lib/rancher/k3s/server/node-token
  - name: Read k3s token
    ansible.builtin.slurp:
      src: /var/lib/rancher/k3s/server/node-token
    register: k3s_token_raw
  - name: decode k3s token
    ansible.builtin.set_fact:
      k3s_token: "{{ k3s_token_raw.content | b64decode | trim }}"
    no_log: true
  - name: Create .kube directory
    ansible.builtin.file:
      state: directory
      path: /home/{{ ansible_user }}/.kube
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0700'
  - name: Copy kubeconfig
    ansible.builtin.copy:
      src: /etc/rancher/k3s/k3s.yaml
      dest: /home/{{ ansible_user }}/.kube/config
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0600'
      remote_src: true
  - name: Export KUBECONFIG
    ansible.builtin.lineinfile:
      path : /home/{{ ansible_user }}/.bashrc
      regexp: '^export KUBECONFIG='
      line : 'export KUBECONFIG=$HOME/.kube/config'
