---
  - name: Download k3s install script
    ansible.builtin.get_url:
      url: "https://raw.githubusercontent.com/k3s-io/k3s/{{ k3s_version }}/install.sh"
      dest: /usr/local/bin/k3s-install.sh
      mode: '0755'

  - name: Install k3s agent
    ansible.builtin.command: /usr/local/bin/k3s-install.sh
    environment:
      INSTALL_K3S_VERSION: "{{ k3s_version }}"
      K3S_URL: "https://{{ hostvars[groups['master'][0]].ansible_host }}:6443"
      K3S_TOKEN: "{{ hostvars[groups['master'][0]].k3s_token }}"
    args:
      creates: /usr/local/bin/k3s
    no_log: true