- name: Common setup for all nodes
  hosts: k3s
  become: true
  roles:
    - common
- name: Setup k3s server
  hosts: master
  become: true
  roles:
    - k3s_server
- name: Setup k3s agent
  hosts: workers
  become: true
  roles:
    - k3s_agent