permissions:
  contents: read
  packages: write

name: Build Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag (e.g. v2026.03.06)'
        required: true
        default: ''

jobs:

  Build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        run: |
          docker build -t ghcr.io/thanutgit/devopsminiproject:${{ github.event.inputs.tag }} .

      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          docker push ghcr.io/thanutgit/devopsminiproject:${{ github.event.inputs.tag }}