permissions:
  contents: read
  packages: write

name: Build Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag (e.g. v2026.03.06)'
        required: true
        default: ''

jobs:

  Build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:  
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Check if tag exists
        run: |
          if docker manifest inspect ghcr.io/thanutgit/devopsminiproject:${{ github.event.inputs.tag }} > /dev/null 2>&1; then
            echo "❌ Image tag ${{ github.event.inputs.tag }} already exists!"
            exit 1
          fi

      - name: Build Image
        run: |
          docker build \
          --build-arg VERSION=${{ github.event.inputs.tag }} \
          --build-arg BUILD_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ) \
          -t ghcr.io/thanutgit/devopsminiproject:${{ github.event.inputs.tag }} .

      - name: Push image
        run: |
          docker push ghcr.io/thanutgit/devopsminiproject:${{ github.event.inputs.tag }}