permissions:
  contents: read
  packages: write

name: Deploy App

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag (e.g. v2026.03.06)'
        required: true
        default: ''
      environment:
        description: 'Environment'
        required: true
        type: choice
        options: 
          - dev
          - prd

jobs:

  Deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ${{ github.event.inputs.environment == 'dev' && 'VirtualBox' || 'VPS' }}
    env:
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    steps:
      - uses: actions/checkout@v4

      - name: Update image tag
        run: |
          sed -i 's|image: ghcr.io/thanutgit/devopsminiproject:.*|image: ghcr.io/thanutgit/devopsminiproject-${{ github.event.inputs.environment }}:${{ github.event.inputs.tag }}|' k8s/job.yaml
          sed -i 's|image: ghcr.io/thanutgit/devopsminiproject:.*|image: ghcr.io/thanutgit/devopsminiproject-${{ github.event.inputs.environment }}:${{ github.event.inputs.tag }}|' k8s/app.yaml

      - name : Deploy to K3s
        run : |
          set -e
          cd k8s
          kubectl apply -f secret.yaml
          kubectl apply -f configmap.yaml
          kubectl delete job devops-project-job -n devops-project --ignore-not-found
          kubectl apply -f job.yaml
          kubectl -n devops-project wait --for=condition=complete job/devops-project-job --timeout=30m 
          kubectl apply -f app.yaml
          kubectl rollout restart deployment/app-api -n devops-project
          kubectl rollout status deployment/app-api -n devops-project --timeout=30m
          kubectl apply -f hpa.yaml
