permissions:
  contents: read
  packages: write

name: Deploy App

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag (e.g. v20260306)'
        required: true
        default: ''

jobs:

  Deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name : test
        run : |
          set -e
          echo "kuy"
